version: '3'

services:
  app:
    build: .
    ports:
    - "80:80"
    environment:
    - DB=mongodb://mongodb:27017
    depends_on:
    - mongodb
    links:
    - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
    - MONGO_DATA_DIR=/usr/data/db
    volumes:
    - /tmp/db:/usr/data/db
    ports:
    - 27017:27017
    command: --smallfiles
